SPREADSHEET_ID = '1FEdZ6HLUzO373k83tOCNLSqnoSd_3ZXRJMc37TjQbHI'

project_id= "tdls-439113"

client_id= "171476710482-do1a87vu5dqj914e0d58afbkphsagq7p.apps.googleusercontent.com"

client_secret="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"